/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package gui;

import java.awt.Image;
import java.sql.ResultSet;
import java.util.Vector;
import java.util.regex.Pattern;
import javax.swing.DefaultComboBoxModel;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.MySQL;

/**
 *
 * @author NIDULA
 */
public class SetQuantity extends javax.swing.JDialog {

    CashierHome cs;

    /**
     * Creates new form SetQuantity
     */
    public SetQuantity(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        ImageIcon i = new ImageIcon("src/resources/logomain.png");
        Image x = i.getImage();
        setIconImage(x);
    }

    public SetQuantity(CashierHome parent, boolean modal, String pname, String pid, String unit) {
        super(parent, modal);
        initComponents();
        ImageIcon i = new ImageIcon("src/resources/logomain.png");
        Image x = i.getImage();
        setIconImage(x);
        loadQtyUnits(pid);
        jComboBox1.setSelectedItem(unit);
        jLabel2.setText(pname);
        this.cs = parent;
    }

    public void loadQtyUnits(String pid) {
        try {
            ResultSet rs = MySQL.search("(SELECT * FROM `qty_units` INNER JOIN `qty_type` ON `qty_type`.`id` = `qty_units`.`qty_type_id` LEFT JOIN `product` ON `product`.`qty_type_id` = `qty_type`.`id` WHERE `product`.`id` = '" + pid + "') UNION (SELECT * FROM `qty_units` INNER JOIN `qty_type` ON `qty_type`.`id` = `qty_units`.`qty_type_id` RIGHT JOIN `product` ON `product`.`qty_type_id` = `qty_type`.`id` WHERE `product`.`id` = '" + pid + "');");
            Vector v = new Vector();
            v.add("Select");
            while (rs.next()) {
                v.add(rs.getString("name"));
            }
            DefaultComboBoxModel dcm = new DefaultComboBoxModel(v);
            jComboBox1.setModel(dcm);

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Quantity");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel1.setText("Product");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("jLabel2");

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jTextField1.setToolTipText("Enter quantity ");
        jTextField1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jTextField1KeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTextField1KeyReleased(evt);
            }
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField1KeyTyped(evt);
            }
        });

        jComboBox1.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jComboBox1.setToolTipText("Select unit");
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jComboBox1KeyPressed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(153, 153, 0));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Set Quantity");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 264, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(47, 47, 47)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 193, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                    .addComponent(jComboBox1))
                .addGap(34, 34, 34)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String qty = jTextField1.getText();
        String qtyUnit = jComboBox1.getSelectedItem().toString();
        try {

            if (qty.isBlank()) {
                JOptionPane.showMessageDialog(this, "Enter The Qty.", "Warning", JOptionPane.WARNING_MESSAGE);
            } else if (qtyUnit.equals("Select")) {
                JOptionPane.showMessageDialog(this, "Enter Quantity Unit.", "Warning", JOptionPane.WARNING_MESSAGE);
            } else {
                //Stock multiplication
                int selectedRowOfTable1 = this.cs.jTable1.getSelectedRow();
                ResultSet stockMultirs = MySQL.search("SELECT * FROM `qty_units` WHERE `name` = '" + this.cs.jTable1.getValueAt(selectedRowOfTable1, 4).toString() + "';");
                stockMultirs.next();
                double stmul = Double.parseDouble(stockMultirs.getString("multiplication"));
                //Stock multiplication

                //new multiplication
                ResultSet newMultirs = MySQL.search("SELECT * FROM `qty_units` WHERE `name` = '" + qtyUnit + "';");
                newMultirs.next();
                double stmulnew = Double.parseDouble(newMultirs.getString("multiplication"));
                //new multiplication

                double enteredQty = Double.parseDouble(qty);
                double stockQty = Double.parseDouble(this.cs.jTable1.getValueAt(selectedRowOfTable1, 3).toString());
                System.out.println(enteredQty * stmul * stmulnew);
                if ((enteredQty * stmul * stmulnew) > stockQty) {
                    JOptionPane.showMessageDialog(this, "Invalid Quantity. Enter Quantity below " + String.valueOf(stockQty) + " " + this.cs.jTable1.getValueAt(selectedRowOfTable1, 4).toString(), "Warning", JOptionPane.WARNING_MESSAGE);
                } else {

                    boolean isThere = false;
                    int r = -1;
                    for (int i = 0; i < this.cs.jTable2.getRowCount(); i++) {
                        if (this.cs.jTable2.getValueAt(i, 0).toString().equals((this.cs.jTable1.getValueAt(selectedRowOfTable1, 0).toString()))) {
                            isThere = true;
                            r = i;
                            break;
                        }
                    }

                    if (isThere) {
                        int con = JOptionPane.showConfirmDialog(this, "This Product Already Added. Do you want to update the quantity?", "Warning", JOptionPane.YES_NO_OPTION, JOptionPane.WARNING_MESSAGE);
                        if (con == JOptionPane.YES_OPTION) {
                            ResultSet qtyUnitMulOld = MySQL.search("SELECT * FROM `qty_units` WHERE `name` = '" + this.cs.jTable2.getValueAt(r, 3).toString() + "';");
                            qtyUnitMulOld.next();
                            double mulOld = Double.parseDouble(qtyUnitMulOld.getString("multiplication"));
                            double oldQty = Double.parseDouble(this.cs.jTable2.getValueAt(r, 2).toString());
                            double newQty = oldQty + (enteredQty * stmulnew * mulOld);
                            if ((newQty * stmul * mulOld) > stockQty) {
                                JOptionPane.showMessageDialog(this, "Invalid Quantity. Enter Quantity below " + String.valueOf(stockQty - oldQty) + " " + this.cs.jTable1.getValueAt(selectedRowOfTable1, 4).toString(), "Warning", JOptionPane.WARNING_MESSAGE);
                            } else {
                                this.cs.jTable2.setValueAt(String.valueOf(newQty), r, 2);
                                this.cs.jTable2.setValueAt(String.valueOf(newQty * Double.parseDouble(this.cs.jTable1.getValueAt(selectedRowOfTable1, 2).toString())), r, 4);
                                this.cs.calculateTotal();
                                this.dispose();
                            }
                        }
                    } else {
                        DefaultTableModel dtm = (DefaultTableModel) this.cs.jTable2.getModel();
                        Vector v = new Vector();
                        v.add(this.cs.jTable1.getValueAt(selectedRowOfTable1, 0).toString());
                        v.add(this.cs.jTable1.getValueAt(selectedRowOfTable1, 1).toString());
                        v.add(String.valueOf(enteredQty));
                        v.add(jComboBox1.getSelectedItem().toString());
                        v.add(String.valueOf(enteredQty * stmul * stmulnew * Double.parseDouble(this.cs.jTable1.getValueAt(selectedRowOfTable1, 2).toString())));
                        dtm.addRow(v);
                        this.cs.calculateTotal();
                        this.dispose();
                    }

                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTextField1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyPressed
        if (evt.getKeyCode() == 10) {
            jComboBox1.grabFocus();
        }
    }//GEN-LAST:event_jTextField1KeyPressed

    private void jTextField1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1KeyReleased

    private void jTextField1KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField1KeyTyped
        String qty = jTextField1.getText();

        String text = qty + evt.getKeyChar();

        if (!Pattern.compile("0|0[.]|0.[1-9]|0.[1-9][0-9]|[1-9][0-9]*[.]?[0-9]{0,2}").matcher(text).matches()) {
            evt.consume();

        }
    }//GEN-LAST:event_jTextField1KeyTyped

    private void jComboBox1KeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jComboBox1KeyPressed
        if (evt.getKeyCode() == 10) {
            jButton1ActionPerformed(null);
        }
    }//GEN-LAST:event_jComboBox1KeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SetQuantity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SetQuantity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SetQuantity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SetQuantity.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SetQuantity dialog = new SetQuantity(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
